//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobsFinder.Exceptions {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceMensagensDeErro {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceMensagensDeErro() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JobsFinder.Exceptions.ResourceMensagensDeErro", typeof(ResourceMensagensDeErro).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro desconhecido.
        /// </summary>
        public static string Erro_Desconhecido {
            get {
                return ResourceManager.GetString("Erro_Desconhecido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado é obrigatório.
        /// </summary>
        public static string Estado_Vazio {
            get {
                return ResourceManager.GetString("Estado_Vazio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cidade já cadastrada com o código Ibge informado.
        /// </summary>
        public static string Ibge_Cadastrado {
            get {
                return ResourceManager.GetString("Ibge_Cadastrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código IBGE é obrigatório.
        /// </summary>
        public static string Ibge_Vazio {
            get {
                return ResourceManager.GetString("Ibge_Vazio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome da cidade não deve ser em branco..
        /// </summary>
        public static string Nome_Cidade_EmBranco {
            get {
                return ResourceManager.GetString("Nome_Cidade_EmBranco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome da cidade não pode ser vazio..
        /// </summary>
        public static string Nome_Cidade_Vazia {
            get {
                return ResourceManager.GetString("Nome_Cidade_Vazia", resourceCulture);
            }
        }
    }
}
